# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  database: hostess_dev
  encoding: utf8
  host: localhost
  password: h05t3ss*d3v 
  pool: 20
  port: 3306
  reconnect: false  
  username: hostess_dev
  

preview:
  adapter: mysql2
  database: hostess_preview
  encoding: utf8
  host: localhost
  password: h05t3ss*pr3v13w
  pool: 20
  port: 3306
  reconnect: false  
  username: hostess_pre

  
  
production:
  adapter: mysql2
  database: hostess
  encoding: utf8
  host: localhost
  password: h05t3ss*pr0duct10n
  pool: 20
  port: 3306
  reconnect: false  
  username: hostess_prod
    

# Bu1ld1ng!










